repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check .
        language: system
        types: [python]
        pass_filenames: true

      - id: ruff-format
        name: ruff format
        entry: ruff format --
        language: system
        types: [python]
        pass_filenames: true
        args: ["--check"]

      - id: mypy
        name: mypy type check
        entry: mypy src/
        language: system
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: pytest --cov=src/ --cov-report=term-missing
        language: system
        types: [python]
        pass_filenames: false